import './js/renderGenres';
import './js/onLoadHomePage';
import './js/eventLisners';
import './js/backToTopBut';
import './js/auth';
import './js/modalInfo';
import './js/loadModalInfo';
import './js/trailer';
import '../node_modules/basiclightbox/dist/basicLightbox.min.css';
